import { useAuth } from '../context/AuthContext';

/** Публичный хук: гайды, комментарии, версии */
export function useGuides() {
  const {
    guides,
    guideComments,
    guideVersions,
    guidesLoaded,
    guideMetaLoaded,
    guidesHasMore,
    guidesTotal,
    guidesLoading,
    ensureGuidesLoaded,
    ensureGuideMetaLoaded,
    loadMoreGuides,
    searchGuidesList,
    searchGuidesRemote,
    addGuide,
    updateGuide,
    deleteGuide,
    getGuideVersions,
    restoreGuideVersion,
    addGuideComment,
    deleteGuideComment,
    toggleGuideCommentLike,
  } = useAuth();
  return {
    guides,
    guideComments,
    guideVersions,
    guidesLoaded,
    guideMetaLoaded,
    guidesHasMore,
    guidesTotal,
    guidesLoading,
    ensureGuidesLoaded,
    ensureGuideMetaLoaded,
    loadMoreGuides,
    searchGuidesList,
    searchGuidesRemote,
    addGuide,
    updateGuide,
    deleteGuide,
    getGuideVersions,
    restoreGuideVersion,
    addGuideComment,
    deleteGuideComment,
    toggleGuideCommentLike,
  };
}
