/**
 * Генерирует public/robots.txt и public/sitemap.xml из src/seo/routes.json
 * и карточек вики (сиды + внутренний путь).
 * Запускается перед сборкой (npm run build).
 */
import { readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { createServer } from 'vite';
import { buildInnerPathWikiArticles } from './innerPathWiki.mjs';
const __dirname = dirname(fileURLToPath(import.meta.url));
const root = join(__dirname, '..');
const siteUrl = (process.env.VITE_SITE_URL || process.env.SITE_URL || 'https://wwm-wiki-nocthra.ru').replace(/\/$/, '');
const buildTime = process.env.VITE_BUILD_TIME || new Date().toISOString();
const pkg = JSON.parse(readFileSync(join(root, 'package.json'), 'utf8'));
const routes = JSON.parse(readFileSync(join(root, 'src/seo/routes.json'), 'utf8'));
const publicRoutes = routes
  .filter((r) => !r.noindex)
  .sort((a, b) => (b.priority ?? 0.5) - (a.priority ?? 0.5) || a.path.localeCompare(b.path));
/** Ожидаемые публичные разделы — предупреждение при пропуске в routes.json */
const EXPECTED_PUBLIC_IDS = [
  'home', 'wwmwiki', 'guides',
  'weapons', 'builds', 'sects', 'bosses', 'npcs', 'riddles',
  'innerpath', 'mystic', 'cooking', 'lifeskills', 'tips',
  'guilds', 'faq', 'suggestions', 'users',
];
const indexedIds = new Set(publicRoutes.map((r) => r.id));
for (const id of EXPECTED_PUBLIC_IDS) {
  if (!indexedIds.has(id)) {
    console.warn(`[seo] WARNING: missing public route id="${id}" in src/seo/routes.json`);
  }
}
/** Разделы с карточками #wiki-card-… (ContentPage + SectionWikiCard) */
const WIKI_CARD_SECTIONS = new Set([
  'weapons', 'builds', 'sects', 'bosses', 'mystic', 'cooking', 'tips', 'lifeskills', 'innerpath',
]);
const pathBySectionId = new Map(
  publicRoutes.map((r) => [r.id, r.path === '/' ? '/' : r.path]),
);
async function loadWikiCardArticles() {
  const server = await createServer({
    root,
    configFile: join(root, 'vite.config.ts'),
    logLevel: 'error',
  });
  try {
    const mod = await server.ssrLoadModule('/scripts/wikiSeeds.ts');
    return [...mod.getAllSeedArticles(), ...buildInnerPathWikiArticles()];
  } finally {
    await server.close();
  }
}
function buildWikiCardRoutes(articles) {
  const seen = new Set();
  const entries = [];
  for (const article of articles) {
    if (!WIKI_CARD_SECTIONS.has(article.section)) continue;
    const basePath = pathBySectionId.get(article.section);
    if (!basePath || !article.id) continue;
    const path = `${basePath}#wiki-card-${article.id}`;
    if (seen.has(path)) continue;
    seen.add(path);
    entries.push({
      path,
      changefreq: 'monthly',
      priority: 0.55,
    });
  }
  return entries.sort((a, b) => a.path.localeCompare(b.path));
}
function formatSitemapUrl(path, changefreq, priority, lastmod) {
  const loc = `${siteUrl}${path === '/' ? '/' : path}`;
  return `  <url>
    <loc>${loc}</loc>
    <xhtml:link rel="alternate" hreflang="ru" href="${loc}" />
    <lastmod>${lastmod}</lastmod>
    <changefreq>${changefreq}</changefreq>
    <priority>${priority}</priority>
  </url>`;
}
async function main() {
  const today = new Date().toISOString().slice(0, 10);
  let wikiCardRoutes = [];
  try {
    const articles = await loadWikiCardArticles();
    wikiCardRoutes = buildWikiCardRoutes(articles);
    console.log(`[seo] wiki cards: ${wikiCardRoutes.length} deep links`);
  } catch (err) {
    console.warn('[seo] WARNING: wiki card URLs skipped:', err?.message || err);
  }
  const sectionEntries = publicRoutes.map((r) =>
    formatSitemapUrl(r.path, r.changefreq || 'weekly', r.priority ?? 0.5, today),
  );
  const cardEntries = wikiCardRoutes.map((r) =>
    formatSitemapUrl(r.path, r.changefreq, r.priority, today),
  );
  const sitemap = `<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by scripts/generate-seo.mjs — do not edit manually -->
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9"
        xmlns:xhtml="http://www.w3.org/1999/xhtml">
${[...sectionEntries, ...cardEntries].join('\n')}
</urlset>
`;
  const robots = `# WWM Wiki — robots.txt (Google, Яндекс, Bing)
User-agent: *
Allow: /
Disallow: /admin
Disallow: /staffchat

User-agent: Googlebot
Allow: /

User-agent: Yandex
Allow: /
Disallow: /admin
Disallow: /staffchat

# Главное зеркало для Яндекса (без www)
Host: ${siteUrl.replace(/^https?:\/\//, '')}

Sitemap: ${siteUrl}/sitemap.xml
`;
  writeFileSync(join(root, 'public/sitemap.xml'), sitemap, 'utf8');
  writeFileSync(join(root, 'public/robots.txt'), robots, 'utf8');
  const buildMeta = { buildTime, siteUrl, version: pkg.version || '0.0.0' };
  writeFileSync(join(root, 'public/health.json'), `${JSON.stringify({ ok: true, ...buildMeta })}\n`, 'utf8');
  writeFileSync(join(root, '.build-meta.json'), `${JSON.stringify(buildMeta)}\n`, 'utf8');
  const totalUrls = publicRoutes.length + wikiCardRoutes.length;
  console.log(`[seo] SITE_URL=${siteUrl}`);
  console.log(`[seo] sitemap: ${totalUrls} URLs (${publicRoutes.length} pages + ${wikiCardRoutes.length} wiki cards) → public/sitemap.xml`);
  console.log('[seo] robots.txt → public/robots.txt');
  console.log(`[seo] health.json buildTime=${buildTime}`);
}
main().catch((err) => {
  console.error('[seo] FATAL:', err);
  process.exit(1);
});
